// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fsjgumvtbskgofszudnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzamd1bXZ0YnNrZ29mc3p1ZG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzQzNDksImV4cCI6MjA3NDI1MDM0OX0.2n2dAH14pDvTSG1Yc8elUGQqPQmPPn6xWoAMWRb07ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);